// <auto-generated />
using System;
using InventorySystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventorySystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventorySystem.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8565),
                            Description = "Electronic devices and accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8568),
                            Description = "Apparel and fashion items",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8569),
                            Description = "Office equipment and stationery",
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8601),
                            Description = "Household appliances and equipment",
                            Name = "Home Appliances"
                        });
                });

            modelBuilder.Entity("InventorySystem.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8892),
                            Description = "Ergonomic wireless mouse with USB receiver",
                            ImageUrl = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400",
                            MinimumStockLevel = 15,
                            Name = "Wireless Mouse",
                            QuantityInStock = 0,
                            SKU = "ELEC-001",
                            SupplierId = 1,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8894),
                            Description = "RGB mechanical gaming keyboard",
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400",
                            MinimumStockLevel = 10,
                            Name = "Mechanical Keyboard",
                            QuantityInStock = 0,
                            SKU = "ELEC-002",
                            SupplierId = 1,
                            UnitPrice = 89.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8896),
                            Description = "7-in-1 USB-C multiport adapter",
                            ImageUrl = "https://images.unsplash.com/photo-1625948515291-69613efd103f?w=400",
                            MinimumStockLevel = 20,
                            Name = "USB-C Hub",
                            QuantityInStock = 0,
                            SKU = "ELEC-003",
                            SupplierId = 1,
                            UnitPrice = 49.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8898),
                            Description = "100% cotton crew neck t-shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
                            MinimumStockLevel = 30,
                            Name = "Cotton T-Shirt",
                            QuantityInStock = 0,
                            SKU = "CLTH-001",
                            SupplierId = 2,
                            UnitPrice = 19.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8900),
                            Description = "Classic fit denim jeans",
                            ImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400",
                            MinimumStockLevel = 25,
                            Name = "Denim Jeans",
                            QuantityInStock = 0,
                            SKU = "CLTH-002",
                            SupplierId = 2,
                            UnitPrice = 59.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8902),
                            Description = "LED desk lamp with adjustable brightness",
                            ImageUrl = "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400",
                            MinimumStockLevel = 15,
                            Name = "Office Desk Lamp",
                            QuantityInStock = 0,
                            SKU = "OFF-001",
                            SupplierId = 3,
                            UnitPrice = 39.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8904),
                            Description = "Pack of 5 ruled notebooks",
                            ImageUrl = "https://images.unsplash.com/photo-1517842645767-c639042777db?w=400",
                            MinimumStockLevel = 40,
                            Name = "Notebook Set",
                            QuantityInStock = 0,
                            SKU = "OFF-002",
                            SupplierId = 3,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8905),
                            Description = "Box of 50 blue ballpoint pens",
                            ImageUrl = "https://images.unsplash.com/photo-1586951728566-d1293c2e8c7d?w=400",
                            MinimumStockLevel = 50,
                            Name = "Ballpoint Pens",
                            QuantityInStock = 0,
                            SKU = "OFF-003",
                            SupplierId = 3,
                            UnitPrice = 15.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8907),
                            Description = "12-cup programmable coffee maker",
                            ImageUrl = "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=400",
                            MinimumStockLevel = 8,
                            Name = "Coffee Maker",
                            QuantityInStock = 0,
                            SKU = "HOME-001",
                            SupplierId = 1,
                            UnitPrice = 79.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8909),
                            Description = "Cordless stick vacuum cleaner",
                            ImageUrl = "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400",
                            MinimumStockLevel = 5,
                            Name = "Vacuum Cleaner",
                            QuantityInStock = 0,
                            SKU = "HOME-002",
                            SupplierId = 2,
                            UnitPrice = 199.99m
                        });
                });

            modelBuilder.Entity("InventorySystem.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("InventorySystem.Models.PurchaseOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("InventorySystem.Models.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("InventorySystem.Models.SalesOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("SalesOrderItems");
                });

            modelBuilder.Entity("InventorySystem.Models.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("InventorySystem.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Tech Street, Silicon Valley, CA 94025",
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8859),
                            Email = "contact@techsolutions.com",
                            Name = "Tech Solutions Inc.",
                            Phone = "+1-555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Commerce Ave, New York, NY 10001",
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8860),
                            Email = "info@globaltraders.com",
                            Name = "Global Traders Ltd.",
                            Phone = "+1-555-0102"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Business Blvd, Chicago, IL 60601",
                            CreatedAt = new DateTime(2025, 12, 11, 0, 28, 38, 805, DateTimeKind.Local).AddTicks(8861),
                            Email = "sales@qualitysuppliers.com",
                            Name = "Quality Suppliers Co.",
                            Phone = "+1-555-0103"
                        });
                });

            modelBuilder.Entity("InventorySystem.Models.Product", b =>
                {
                    b.HasOne("InventorySystem.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySystem.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventorySystem.Models.PurchaseOrder", b =>
                {
                    b.HasOne("InventorySystem.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventorySystem.Models.PurchaseOrderItem", b =>
                {
                    b.HasOne("InventorySystem.Models.Product", "Product")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySystem.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("InventorySystem.Models.SalesOrderItem", b =>
                {
                    b.HasOne("InventorySystem.Models.Product", "Product")
                        .WithMany("SalesOrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySystem.Models.SalesOrder", "SalesOrder")
                        .WithMany("Items")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("InventorySystem.Models.StockTransaction", b =>
                {
                    b.HasOne("InventorySystem.Models.Product", "Product")
                        .WithMany("StockTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventorySystem.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventorySystem.Models.Product", b =>
                {
                    b.Navigation("PurchaseOrderItems");

                    b.Navigation("SalesOrderItems");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("InventorySystem.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InventorySystem.Models.SalesOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InventorySystem.Models.Supplier", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
